version: "3.9"
services:
  cert-generator:
    build: .
    container_name: cert-generator
    ports:
      - "19001:8000"
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Sao_Paulo
